### ISSUE TITLE
Is there a plan to move this into SublimeLinter org?

### ISSUE THREAD

**Issue by tonyjiangh** [Tadly/SublimeLinter-pycodestyle#1]
SSIA
There's a closed PR talking about forking the old pep8 linter into a pycodestyle one.
So I guess merging it would be a good idea?

**Comment by Tadly** [comment]
Didn't realize I still had this... wait. It's not even a fork?
What was I doing. Anyways.
I moved away from sublime so you may take this and do whatever you want with it :)

**Comment by tonyjiangh** [comment]
Gotya.
